### PR TITLE
Connection url ends in trailing forward slash

### LINKED ISSUE #48: [BUG] There is no obvious way to support a reverse proxy
**Describe the bug**
When running towards elasticsearch behind a reverse proxy where the url is something like `http://10.1.2.3/es/` I haven't found a way to use it. The reason for this appears to be the way `Url::join` works. When given a path that starts with `/` it removes everything after the domain and adds it to the root.

**To Reproduce**

```rust
    // The logging from reqwuest shows how the url is not as expected
    let client = Elasticsearch::new(Transport::single_node("http://10.1.2.3/es/")?);
    let search = client.search(SearchParts::Index(&["my-index"]));
    let res = search.send().await?;
    // [2020-01-14T10:25:31Z DEBUG reqwest::async_impl::response] Response: '200 OK' for https://10.1.2.3/my-index/_search

    // Digging further shows the issue is likely in how Url::join works
    let url = url::Url::parse("http://10.1.2.3/hello/").unwrap();
    assert_eq!(url.join("world").unwrap().as_str(), "http://10.1.2.3/hello/world");
    assert_eq!(url.join("/world").unwrap().as_str(), "http://10.1.2.3/world");

    // Note: The trailing backslash is important or it will be consithered a file name
    let url = url::Url::parse("http://10.1.2.3/hello/again").unwrap();
    assert_eq!(url.join("world").unwrap().as_str(), "http://10.1.2.3/hello/world");
    assert_eq!(url.join("/world").unwrap().as_str(), "http://10.1.2.3/world");
```

**Expected behavior**
The url used should be `https://10.1.2.3/es/my-index/_search`

**Environment (please complete the following information):**
 - OS: Probably doesn't matter. Tested on Windows and Linux
 - rustc version: rustc 1.42.0-nightly (859764425 2020-01-07)

### PR DESCRIPTION
**Pull request by russcam**
This PR fixes a bug in relation to the usage of url::join(). If A url
passed to Connection does not end in a trailing forward slash, a new url
will be constructed from the passed url with a trailing forward slash. When
joining a Connection url with an API path, the leading forward slash of the
path is trimmed, so that the path is appended to the url rather than replacing
any existing path segments.

Fixes #48

### CODE REVIEW

File: elasticsearch/src/http/transport.rs [hunk 1]
```diff
@@ -175,8 +175,17 @@ pub struct Connection {
 }
 
 impl Connection {
-    /// Creates a new instance of a [Connection]
+    /// Creates a new instance of a [Connection].
+    ///
+    /// If the passed [url::Url] does not have a trailing forward slash, a new
+    /// url is constructed from the passed url with a trailing slash.
```
Comment (russcam) [inline elasticsearch/src/http/transport.rs]:
```suggestion
    /// url is constructed from the passed url, with a trailing slash.
```
